### ISSUE TITLE
Connection Issue: Exasol to Databricks Notebook (Multiple Nodes)

### ISSUE THREAD

**Issue by mohamedaltaleb0** [exasol/spark-connector#218]
Hello everyone,

Firstly, I want to express my gratitude to all of you for your contributions to this project.

I've been working on establishing a connection in a Databricks notebook with Exasol. Below is the code snippet I've been using. However, it seems to only work when I set the max_nodes option to 1, despite there being 8 nodes available.

```python
df = (spark
  .read
  .format("exasol")
  .option("host", "masternodeip")
  .option("port", "port")
  .option("fingerprint", "serverfingerprint")
  .option("max_nodes", "8")
  .option("username", "username")
  .option("password", "password")
  .option("query", "SELECT * FROM DATA.DHEAY")
  .load()
)

display(df)
``` 
Could someone kindly provide assistance on how I should proceed with this? Any insights would be greatly appreciated. Thank you.

**Comment by Shmuma** [comment]
Hi!

Thanks for reaching out!

This option should work. Spark-connector selects minimal value between this parameter and DB Datanodes count to decide about parallelism on reading and writing operations.

The difference between value of 1 and larger numbers is that spark nodes need to be able to establish TCP connection to the DB on ports higher than 20000. If your network blocks such connections, higher values might fail.

In detail, this happens when ``max_nodes > 1``:

- spark code connects to the db asking to created "subconnections" to the datanodes
- DB returns N jdbc connections strings to the spark (where ``N=min(max_nodes,db_nodes)``). 
- spark code establishes N subconnections to the DB using those strings
- parallel data operation is performed.

Could you please check that your network accepts such scenarios?
If everything is ok there, it would be great to get the error message you're getting from the code you sent. Spark worker logs are also might be needed.

Hope this will help!
Wbr, Maxim

**Comment by kaklakariada** [comment]
@mohamedaltaleb0 We will close this. If you have further questions please feel free to re-open this.
